[package]
name = "qingyin-ui-bridge"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
cstr.workspace = true
image.workspace = true
qmetaobject.workspace = true
qingyin-chinese = { path = "../chinese" }
qingyin-core = { path = "../core" }
qingyin-library = { path = "../library" }
qingyin-metadata = { path = "../metadata" }
qingyin-player = { path = "../player" }
qingyin-storage = { path = "../storage" }
qttypes = { version = "0.2.12", features = ["qtquick"] }
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

[build-dependencies]
cc = "1"
qttypes = { version = "0.2.12", features = ["qtquick"] }

[lints]
workspace = true
